---
title: "Adherence using CMA (continuous multiple-interval measures of medication availability/gaps)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro to CMA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Examples of how CMA is calculated

The goal is to help users select correct CMA for their work.

<https://www.adherer.eu/adherence/>

```{r,echo = FALSE}
sample_data <- data.frame(
  person_id = c(1, 1, 1, 1, 1, 2, 2, 2, 3),
  drug_concept_id = c(1, 1, 1, 1, 1, 1, 1, 1, 1),
  drug_exposure_start_date = c(
    as.Date("2010-12-02"),
    as.Date("2011-05-31"),
    as.Date("2011-06-30"),
    as.Date("2011-12-27"),
    as.Date("2012-03-26"),
    as.Date("2011-05-31"),
    # // other patient
    as.Date("2011-06-30"),
    as.Date("2011-12-27"),
    #
    as.Date("2011-06-30") # // last pt
    # as.Date("2011-12-27")
  ),
  days_supply = c(60, 30, 90, 180, 180, 60, 90, 30, 90),
  cohort_start_date = rep(c(as.Date("2011-01-06")), times = 9),
  cohort_end_date = rep(c(as.Date("2012-05-01")), times = 9),
  observation_period_start_date = rep(c(as.Date("2009-11-07")),
    times =
      9
  ),
  observation_period_end_date = rep(c(as.Date("2013-06-01")), times = 9)
)

sample_data <- dplyr::mutate(sample_data,
  observation_period_duration = as.integer(.data$cohort_end_date - .data$cohort_start_date),
  followup_period_duration = as.integer(observation_period_end_date - observation_period_start_date),
  observation_window_start = cohort_start_date
)
```

```{r, message=FALSE, results='hide',echo = FALSE}
cma <- c("CMA1", "CMA2", "CMA3", "CMA4", "CMA5", "CMA6", "CMA7", "CMA8", "CMA9")
cma_values <- vector("list")

for (i in cma) {
  cli::cli_alert_info("Calculating { i }.")

  result <- eval(rlang::parse_expr(
    paste0(
      "AdhereR::",
      i,
      '(
      data = sample_data,
      ID.colname = "person_id",
      event.date.colname = "drug_exposure_start_date",
      event.duration.colname = "days_supply",
      medication.class.colname = "drug_concept_id",
      observation.window.start = "observation_window_start",
      observation.window.duration = "observation_period_duration",
      observation.window.duration.unit = "days",
      followup.window.duration = "followup_period_duration",
      followup.window.start = "observation_period_start_date"
    )'
    )
  ))

  cma_values[[i]] <- result
}
```

## CMA1

```{r,warning = FALSE}
plot(cma_values$CMA1, show.legend = TRUE, align.all.patients = FALSE, align.first.event.at.zero = TRUE, period.in.days = 60)
# comments from code
# # For less than two events or when the first and the last events are on the same day, CMA1 does not make sense
# # Otherwise, the sum of durations of the events excluding the last divided by the number of days between the first and the last event
# first:  (60+90) / 210
# second: (30+90+180) / 300
```

## CMA2

```{r,warning = FALSE}
plot(cma_values$CMA2, show.legend = FALSE, align.all.patients = FALSE, align.first.event.at.zero = TRUE, period.in.days = 60)
# (numberof dayssupplyincludinglastevent)/(firsttolastevent)
# Comments from code:
# For less than one event or when the first event is on the last day of the observation window, CMA2 does not make sense
# Otherwise, the sum of durations of the events divided by the number of days between the first event and the end of the observation window 
# 60 + 90 + 30 / 336
# 30 + 90 + 180 + 180 / 336
```

## CMA 3 & 4

same as 1 & 2 only to be capped at 100%

## CMA 5

```{r,warning = FALSE}
plot(cma_values$CMA5, show.legend = FALSE, align.all.patients = FALSE, align.first.event.at.zero = TRUE, period.in.days = 60)
# (numberof daysof theoreticaluse)/(firsttolastevent)
# comment from code: # Otherwise, the sum of durations of the events excluding the last divided by the number of days between the first and the last event
# arvesse võetakse gap days mis jäävad alles kui arvestada ravimite küllusega
# gap days esimesest sündmusest viimase alguseni ja lahuta days supplyd (va viimane)
# First:
# 1 - (60) / 210
# Second
# 1 - (90) / 300
```

## CMA6

```{r,warning = FALSE}
# # First:
# 1 - (60 + 96) / 336
# Second
# 1 - (90) / 336
# (numberof daysof theoreticaluse)/(firsteventtoendofobservationwindow)
plot(cma_values$CMA6, show.legend = FALSE, align.all.patients = FALSE, align.first.event.at.zero = TRUE, period.in.days = 60)
```

## CMA7

```{r, warning = FALSE}
# 1- (145+60+96) / 481
# 1 - (120 + 90) / 481
# (numberof daysof theoreticaluse)/(starttoendof observationwindow)
plot(cma_values$CMA7, period.in.days = 60, show.legend = FALSE)
```

## CMA8

```{r,warning = FALSE}
# (numberof daysof theoreticaluse)/(laggedstarttoendof observationwindow
# 1- (145+60+96) / 481
# 1 - (120 + 90) / (481-25) <- sisse tulev sündmus jääb välja
plot(cma_values$CMA8, period.in.days = 60, show.legend = FALSE)
```

## CMA9

```{r, warning = FALSE}
# number of days in the observation window, each weighted by the ratio
# of days supply applicable to their event interval)
#   /
# (start to end of observation window)

# !take account the overlap with obs window!
# ((1 - 612/702) * 306) / 481
# ((1 - 0/30)*30 + (1 - 60/180)*180 + (1 - 492/522) * 126) / 481
# ((1 - 120/180)*145 + (1 - 0/30)*30 + (1 - 90/180)*180 + (1 - 0/90) * 90 + (1 - 162/432) * 36) / 481
plot(cma_values$CMA9, period.in.days = 60, show.legend = FALSE)
```

```{r,eval = FALSE}
sample_data <- data.frame(
  person_id = c(1, 1, 1, 1, 1, 2, 2, 2, 3),
  drug_concept_id = c(1, 2, 1, 1, 2, 1, 1, 1, 1),
  drug_exposure_start_date = c(
    as.Date("2010-12-02"),
    as.Date("2011-05-31"),
    as.Date("2011-06-30"),
    as.Date("2011-12-27"),
    as.Date("2012-03-26"),
    as.Date("2011-05-31"), # // other patient
    as.Date("2011-06-30"),
    as.Date("2011-12-27"), #
    as.Date("2011-06-30") # // last pt
    # as.Date("2011-12-27")
  ),
  days_supply = c(60, 30, 90, 180, 180, 60, 90, 30, 90),
  cohort_start_date = rep(c(as.Date("2011-01-06")), times = 9),
  cohort_end_date = rep(c(as.Date("2012-05-01")), times = 9),
  observation_period_start_date = rep(c(as.Date("2009-11-07")), times = 9),
  observation_period_end_date = rep(c(as.Date("2013-06-01")), times = 9)
)
```

```{r, eval = FALSE}
sample_data_gpt <- data.frame(
  person_id = c(3),
  drug_concept_id = c(1),
  drug_exposure_start_date = c(
    as.Date("2011-06-30")
  ),
  days_supply = c(90),
  observation_window_start = rep(c(as.Date("2011-01-06")), times = 1),
  observation_window_end = rep(c(as.Date("2012-05-01")), times = 1),
  follow_up_period_start = rep(c(as.Date("2009-11-07")), times = 1),
  follow_up_period_end = rep(c(as.Date("2013-06-01")), times = 1)
)
```
