#' Documentation helper for cdm parameter
#'
#' @param cdm (`cdm_reference`) A CDM reference object created with CDMConnector.
#' @name cdmDoc
#' @keywords internal
NULL

#' Documentation helper for conceptSet parameter
#'
#' @param conceptSet (`list`, `codelist`, or `NULL`) Named list of drug concept IDs.
#'   Recommended to use [CodelistGenerator::getDrugIngredientCodes()].
#'   If `NULL`, all drugs in the drug_exposure table are included.
#' @name conceptSetDoc
#' @keywords internal
NULL

#' Documentation helper for name parameter
#'
#' @param name (`character(1)`) Name for the output table in the database.
#' @name nameDoc
#' @keywords internal
NULL

#' Documentation helper for indexDate parameter
#'
#' @param indexDate (`character(1)`) Name of the column to use as the index date
#'   for patient-level calculations. Default: `"drug_exposure_start_date"`.
#' @name indexDateDoc
#' @keywords internal
NULL

#' Documentation helper for cma parameter
#'
#' @param cma (`character`) Vector of CMA types to calculate. Options:
#'   `"CMA1"` through `"CMA9"`. See [AdhereR documentation](https://www.adherer.eu/)
#'   for details on each CMA type.
#' @name cmaDoc
#' @keywords internal
NULL

#' Documentation helper for drugExposure parameter
#'
#' @param drugExposure Database table reference or data frame containing drug exposure
#'   data with patient information, typically generated by [generateChronicDrugExposure()].
#'   Required columns: person_id, drug_concept_id, drug_exposure_start_date, days_supply.
#' @name drugExposureDoc
#' @keywords internal
NULL

#' Documentation helper for adherenceData parameter
#'
#' @param adherenceData Database table reference or data frame containing adherence
#'   calculation results, typically generated by [calculateAdherence()] or
#'   [calculateAdherenceSlidingWindow()].
#' @name adherenceDataDoc
#' @keywords internal
NULL

#' Documentation helper for medicationGroup parameter
#'
#' @param medicationGroup (`list` or `NULL`) Named list where each element contains
#'   drug_concept_id values for a medication group. CMA is calculated separately for
#'   each group. If `NULL`, all medications are treated as one group.
#' @name medicationGroupDoc
#' @keywords internal
NULL

#' Documentation helper for batchSize parameter
#'
#' @param batchSize (`numeric(1)`) Number of subjects to process in each batch.
#'   Default: 1000. Increase for better performance with large datasets, decrease
#'   if running into memory issues.
#' @name batchSizeDoc
#' @keywords internal
NULL
